name: CI

on: [push, pull_request]

permissions: {}

jobs:
  build:

    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Set up Python
        run: uv python install

      - name: Dependencies
        run: uv sync --all-extras --dev

      - name: Ruff Check
        run: uv run ruff check --output-format=github .

      - name: Ruff Format
        run: uv run ruff format --check .

      - name: pytest
        run: uv run coverage run -m pytest

      - name: coverage
        run: uv run coverage report

      - name: build
        run: uv build
